#Generates an executable: use the executable by typing ./henry_caleb_quickSort input.txt output.txt
henry_caleb_quickSort: henry_caleb_quickSort.cpp
	g++ -std=c++17 -Wall henry_caleb_quickSort.cpp -o henry_caleb_quickSort

clean:
	rm -f henry_caleb_quickSort henry_caleb_executiontime.txt